// <auto-generated />
using System;
using LogicDataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogicDataAccess.Migrations
{
    [DbContext(typeof(PaperFactoryContext))]
    [Migration("20240511202645_changeMethodPriceInLine")]
    partial class changeMethodPriceInLine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BussinesLogic.Entity.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("distance")
                        .HasColumnType("float");

                    b.Property<string>("rut")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("socialReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("rut")
                        .IsUnique();

                    b.ToTable("clients");
                });

            modelBuilder.Entity("BussinesLogic.Entity.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<int>("stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("code")
                        .IsUnique();

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("items");
                });

            modelBuilder.Entity("BussinesLogic.Entity.Line", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<int>("idItem")
                        .HasColumnType("int");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("idItem");

                    b.ToTable("Line");
                });

            modelBuilder.Entity("BussinesLogic.Entity.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<bool>("cancel")
                        .HasColumnType("bit");

                    b.Property<DateTime>("creationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("delivered")
                        .HasColumnType("bit");

                    b.Property<DateTime>("deliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("finalPrice")
                        .HasColumnType("float");

                    b.Property<int>("idClient")
                        .HasColumnType("int");

                    b.Property<bool>("isExrpress")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("idClient");

                    b.ToTable("orders");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Order");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BussinesLogic.Entity.Setting", b =>
                {
                    b.Property<string>("settingName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("settingValue")
                        .HasColumnType("float");

                    b.HasKey("settingName");

                    b.ToTable("settings");
                });

            modelBuilder.Entity("BussinesLogic.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("admi")
                        .HasColumnType("bit");

                    b.Property<string>("encrypt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("pass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("mail")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("BussinesLogic.Entity.Comun", b =>
                {
                    b.HasBaseType("BussinesLogic.Entity.Order");

                    b.HasDiscriminator().HasValue("Comun");
                });

            modelBuilder.Entity("BussinesLogic.Entity.Express", b =>
                {
                    b.HasBaseType("BussinesLogic.Entity.Order");

                    b.HasDiscriminator().HasValue("Express");
                });

            modelBuilder.Entity("BussinesLogic.Entity.Client", b =>
                {
                    b.OwnsOne("BussinesLogic.ValueObject.Client.Location", "location", b1 =>
                        {
                            b1.Property<int>("ClientId")
                                .HasColumnType("int");

                            b1.Property<string>("city")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("number")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("street")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ClientId");

                            b1.ToTable("clients");

                            b1.WithOwner()
                                .HasForeignKey("ClientId");
                        });

                    b.OwnsOne("BussinesLogic.ValueObject.Client.NombreCliente", "nombreCli", b1 =>
                        {
                            b1.Property<int>("ClientId")
                                .HasColumnType("int");

                            b1.Property<string>("name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("surename")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ClientId");

                            b1.ToTable("clients");

                            b1.WithOwner()
                                .HasForeignKey("ClientId");
                        });

                    b.Navigation("location")
                        .IsRequired();

                    b.Navigation("nombreCli")
                        .IsRequired();
                });

            modelBuilder.Entity("BussinesLogic.Entity.Line", b =>
                {
                    b.HasOne("BussinesLogic.Entity.Order", null)
                        .WithMany("lines")
                        .HasForeignKey("OrderId");

                    b.HasOne("BussinesLogic.Entity.Item", "item")
                        .WithMany()
                        .HasForeignKey("idItem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("item");
                });

            modelBuilder.Entity("BussinesLogic.Entity.Order", b =>
                {
                    b.HasOne("BussinesLogic.Entity.Client", "client")
                        .WithMany()
                        .HasForeignKey("idClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("client");
                });

            modelBuilder.Entity("BussinesLogic.Entity.User", b =>
                {
                    b.OwnsOne("BussinesLogic.ValueObject.User.CompleteName", "comName", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("int");

                            b1.Property<string>("name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("surename")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("comName")
                        .IsRequired();
                });

            modelBuilder.Entity("BussinesLogic.Entity.Order", b =>
                {
                    b.Navigation("lines");
                });
#pragma warning restore 612, 618
        }
    }
}
